name: Build Dockerfiles on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfiles in all directories
        run: |
          for dir in */; do
            if [ -f "$dir/Dockerfile" ]; then
              service_name=$(basename "$dir")
            image_name="${{ secrets.DOCKER_HUB_REPO }}-$service_name"
              cd "$dir"
              docker build -t "$image_name:test" .
              cd ..
            fi
          done
