name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          # Add more image names as needed
          - fast-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t zkdevs/${{ matrix.image }} -f ${{ matrix.image }}/Dockerfile .

      - name: Tag Docker image
        run: |
          image_name="zkdevs/${{ matrix.image }}"
          docker tag zkdevs/${{ matrix.image }}:latest "$image_name:${{ github.sha }}"
          docker tag zkdevs/${{ matrix.image }}:latest "$image_name:latest"

      - name: Push Docker image
        run: |
          image_name="zkdevs/${{ matrix.image }}"
          docker push "$image_name:${{ github.sha }}"
          docker push "$image_name:latest"
