name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          # Add more image names as needed
          - fast-api
          - mongo
          - node-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run:  cd ${{ matrix.image }} && docker build -t ghcr.io/zkdevs/${{ matrix.image }} .
      - name: Tag Docker image
        run: |
          image_name="ghcr.io/zkdevs/${{ matrix.image }}"
          docker tag ghcr.io/zkdevs/${{ matrix.image }}:latest "$image_name:${{ github.sha }}"
          docker tag ghcr.io/zkdevs/${{ matrix.image }}:latest "$image_name:latest"

      - name: Push Docker image
        run: |
          image_name="ghcr.io/zkdevs/${{ matrix.image }}"
          docker push "$image_name:${{ github.sha }}"
          docker push "$image_name:latest"
